# Generated by Django 5.0.6 on 2024-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=15)),
                ('kkm_model', models.CharField(max_length=50)),
                ('znm', models.CharField(max_length=50)),
                ('client_login', models.CharField(max_length=50, unique=True)),
                ('client_password', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('end_of_service_date', models.DateField()),
                ('days_count', models.IntegerField()),
            ],
        ),
    ]
