# Generated by Django 5.0.6 on 2024-06-10 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='INN must contain only digits and be up to 14 characters long', regex='^\\d{0,14}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must contain only digits', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[(0, 'Активный'), (1, 'Временный'), (2, 'Снятый с учета')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='znm',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ZNM must contain only letters and digits', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
