# Generated by Django 5.0.6 on 2024-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_inn_alter_client_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_password',
            new_name='password_hash',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_login',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Активный'), (1, 'Временный'), (2, 'Снятый с учета')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='znm',
            field=models.CharField(max_length=50),
        ),
    ]
