# Generated by Django 5.0.6 on 2024-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_client_password_client_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=14),
        ),
    ]
