# Generated by Django 5.0.6 on 2024-06-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='days_count',
        ),
    ]
