# Generated by Django 5.0.6 on 2024-06-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_client_name_alter_client_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_number',
            field=models.IntegerField(),
        ),
    ]
