# Generated by Django 5.0.6 on 2024-06-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_inn_alter_client_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_number',
            field=models.IntegerField(unique=True),
        ),
    ]
