# Generated by Django 5.0.6 on 2024-06-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='znm',
            field=models.CharField(max_length=100),
        ),
    ]
